language: node_js
os: windows

services:
   - docker

before_install:
  - docker build -t cesgo2009/React-project -f Dockerfile.dev

script:
    - docker run  cesgo2009/React-project run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "Docker-project"
 env: "Docker-env"
 bucket_name: ""
 bucket_path: "Docker-project"
 on:
   branch: master
 access_key: $AWS_ACCESS_KEY
 secret_access_key: 
  secure: "$AWS_SECRET_KEY"
 
   